export const brands = [
  {
    brand: 'Nike',
    shoes: ['Air Max', 'Air Force', 'Air Jordan', 'Air Mag', 'Pegasus', 'Kobe'],
    slogan: 'Just Do It',
    logo: 'Swoosh',
    headquarters: 'Portland',
  },
  {
    brand: 'Puma',
    shoes: ['Clyde', 'Suede', 'Roma', 'California'],
    slogan: 'are Forever Faster',
    logo: 'Panther',
    headquarters: 'Herzogenaurach',
  },
  {
    brand: 'Adidas',
    shoes: ['Ultraboost', 'Gazelle', 'Samba', 'Superstar'],
    slogan: 'Impossible Is Nothing',
    logo: 'trefoil',
    headquarters: 'Herzogenaurach',
  },
];

export const countries = [
  {
    id: 72,
    name: 'Ecuador',
    iso2: 'EC',
    iso3: 'ECU',
    local_name: 'Ecuador',
    continent: 'South America',
  },
  {
    id: 129,
    name: 'Lesotho',
    iso2: 'LS',
    iso3: 'LSO',
    local_name: 'Lesotho',
    continent: 'Africa',
  },
  {
    id: 245,
    name: 'Yemen',
    iso2: 'YE',
    iso3: 'YEM',
    local_name: 'Al-Yaman',
    continent: 'Asia',
  },
  {
    id: 197,
    name: 'Saudi Arabia',
    iso2: 'SA',
    iso3: 'SAU',
    local_name: 'Al-Mamlaka al-Arabiya as-Saudiya',
    continent: 'Asia',
  },
  {
    id: 190,
    name: 'Saint Kitts and Nevis',
    iso2: 'KN',
    iso3: 'KNA',
    local_name: 'Saint Kitts and Nevis',
    continent: 'North America',
  },
  {
    id: 200,
    name: 'Sierra Leone',
    iso2: 'SL',
    iso3: 'SLE',
    local_name: 'Sierra Leone',
    continent: 'Africa',
  },
  {
    id: 193,
    name: 'Saint Vincent and the Grenadines',
    iso2: 'VC',
    iso3: 'VCT',
    local_name: 'Saint Vincent and the Grenadines',
    continent: 'North America',
  },
  {
    id: 233,
    name: 'United Kingdom',
    iso2: 'GB',
    iso3: 'GBR',
    local_name: 'United Kingdom',
    continent: 'Europe',
  },
  {
    id: 5,
    name: 'Jersey',
    iso2: 'JE',
    iso3: 'JEY',
    local_name: null,
    continent: null,
  },
  {
    id: 88,
    name: 'Gambia',
    iso2: 'GM',
    iso3: 'GMB',
    local_name: 'The Gambia',
    continent: 'Africa',
  },
  {
    id: 121,
    name: 'Kiribati',
    iso2: 'KI',
    iso3: 'KIR',
    local_name: 'Kiribati',
    continent: 'Oceania',
  },
  {
    id: 209,
    name: 'Sri Lanka',
    iso2: 'LK',
    iso3: 'LKA',
    local_name: 'Sri Lanka/Ilankai',
    continent: 'Asia',
  },
  {
    id: 44,
    name: 'Burkina Faso',
    iso2: 'BF',
    iso3: 'BFA',
    local_name: 'Burkina Faso',
    continent: 'Africa',
  },
  {
    id: 196,
    name: 'Sao Tome and Principe',
    iso2: 'ST',
    iso3: 'STP',
    local_name: 'São Tomé e Príncipe',
    continent: 'Africa',
  },
  {
    id: 49,
    name: 'Cape Verde',
    iso2: 'CV',
    iso3: 'CPV',
    local_name: 'Cabo Verde',
    continent: 'Africa',
  },
  {
    id: 15,
    name: 'Andorra',
    iso2: 'AD',
    iso3: 'AND',
    local_name: 'Andorra',
    continent: 'Europe',
  },
  {
    id: 144,
    name: 'Martinique',
    iso2: 'MQ',
    iso3: 'MTQ',
    local_name: 'Martinique',
    continent: 'North America',
  },
  {
    id: 139,
    name: 'Malaysia',
    iso2: 'MY',
    iso3: 'MYS',
    local_name: 'Malaysia',
    continent: 'Asia',
  },
  {
    id: 145,
    name: 'Mauritania',
    iso2: 'MR',
    iso3: 'MRT',
    local_name: 'Muritaniya/Mauritanie',
    continent: 'Africa',
  },
  {
    id: 117,
    name: 'Japan',
    iso2: 'JP',
    iso3: 'JPN',
    local_name: 'Nihon/Nippon',
    continent: 'Asia',
  },
  {
    id: 103,
    name: 'Heard Island and Mcdonald Islands',
    iso2: 'HM',
    iso3: 'HMD',
    local_name: 'Heard and McDonald Islands',
    continent: 'Antarctica',
  },
  {
    id: 77,
    name: 'Estonia',
    iso2: 'EE',
    iso3: 'EST',
    local_name: 'Eesti',
    continent: 'Europe',
  },
  {
    id: 92,
    name: 'Gibraltar',
    iso2: 'GI',
    iso3: 'GIB',
    local_name: 'Gibraltar',
    continent: 'Europe',
  },
  {
    id: 143,
    name: 'Marshall Islands',
    iso2: 'MH',
    iso3: 'MHL',
    local_name: 'Marshall Islands/Majol',
    continent: 'Oceania',
  },
  {
    id: 85,
    name: 'French Polynesia',
    iso2: 'PF',
    iso3: 'PYF',
    local_name: 'Polynésie française',
    continent: 'Oceania',
  },
  {
    id: 37,
    name: 'Bosnia and Herzegovina',
    iso2: 'BA',
    iso3: 'BIH',
    local_name: 'Bosna i Hercegovina',
    continent: 'Europe',
  },
  {
    id: 143,
    name: 'Marshall Islands',
    iso2: 'MH',
    iso3: 'MHL',
    local_name: 'Marshall Islands/Majol',
    continent: 'Oceania',
  },
];

export const dogs = [
  { name: 'Benny', age: 6 },
  { name: 'Finley', age: 3 },
  { name: 'Ruby', age: 4 },
  { name: 'Spot', age: 2 },
  { name: 'Rover', age: 1 },
];
